package com.example.ffl.fighter;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.List;


@RestController // This means that this class is a Controller,handles our http requests
@RequestMapping(path="/api/fighter") // This means URL's start with /db (after Application path)
public class FighterController {

    private FighterService  fighterService;
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private FighterRepository fighterRepository;

    @Autowired
    //Delegates business logic back to service layer
    public FighterController(FighterService fighterService) {
        this.fighterService = fighterService;
    }

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String name
            , @RequestParam String martialArt, @RequestParam String weightClass, @RequestParam Integer height, @RequestParam String nationality) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Fighter n = new Fighter();
        n.setName(name);
        n.setMartialArt(martialArt);
        n.setHeight(height);
        n.setWeightClass(weightClass);
        n.setNationality(nationality);

        fighterRepository.save(n);
        fighterRepository.saveAndFlush(n);
        return "Saved";
    }


    //Do all parameters later
    @GetMapping
    public @ResponseBody List<Fighter> getFighters(
        @RequestParam(required = false) String name)
    {
        if (name != null)
        {
            return fighterService.getFightersByName(name);
        }
        return null;
    }

    @GetMapping(path="/all")
    public @ResponseBody List<Fighter> getAllFighters() {
        // This returns a JSON or XML with the users
        return fighterRepository.findAll();
    }

    //Handles post requests to add a new player to our database
    @PostMapping
    public ResponseEntity<Fighter> addFighter(@RequestBody Fighter fighter) {
        Fighter createdFighter = fighterService.addFighter(fighter);
        //if success returns 201
        return new ResponseEntity<>(createdFighter, HttpStatus.CREATED);
    }

    @PutMapping //for updates
    public ResponseEntity<Fighter> updateFighter(@RequestBody Fighter fighter) {
        Fighter resultFighter = fighterService.updateFighter(fighter);
        if (resultFighter != null) return new ResponseEntity<>(resultFighter, HttpStatus.OK);
        else return new ResponseEntity<>(HttpStatus.NOT_FOUND);
    }

    @DeleteMapping("/{fighterName}")
    public @ResponseBody ResponseEntity<String> deleteFighter(@PathVariable String fighterName)
    {
        fighterService.deleteFighter(fighterName);
        return new ResponseEntity<>("Fighter Deleted Successfully", HttpStatus.OK);
    }

}