package com.example.ffl.fighter;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/db") // This means URL's start with /db (after Application path)
public class FighterController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private FighterRepository fighterRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String name
            , @RequestParam String martialArt, @RequestParam String weightClass, @RequestParam Integer height, @RequestParam String nationality) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Fighter n = new Fighter();
        n.setName(name);
        n.setMartialArt(martialArt);
        n.setHeight(height);
        n.setWeightClass(weightClass);
        n.setNationality(nationality);

        fighterRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Fighter> getAllUsers() {
        // This returns a JSON or XML with the users
        return fighterRepository.findAll();
    }
}